import { pgTable, text, uuid, timestamp, integer, boolean, jsonb, date, numeric, index } from "drizzle-orm/pg-core";

export const travelHelperRoutes = pgTable(
  "travel_helper_routes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    origin: jsonb("origin").notNull(),
    destination: jsonb("destination").notNull(),
    waypoints: jsonb("waypoints").default([]).notNull(),
    polyline: text("polyline"),
    totalDistanceKm: numeric("total_distance_km", { precision: 10, scale: 2 }),
    totalDurationMinutes: integer("total_duration_minutes"),
    transportMode: text("transport_mode").notNull().default("driving"),
    routeDate: date("route_date"),
    isArchived: boolean("is_archived").default(false).notNull(),
    isFavorite: boolean("is_favorite").default(false).notNull(),
    tags: text("tags").array().default([]).notNull(),
    notes: text("notes"),
    elevationMin: numeric("elevation_min", { precision: 8, scale: 2 }),
    elevationMax: numeric("elevation_max", { precision: 8, scale: 2 }),
    elevationGain: numeric("elevation_gain", { precision: 8, scale: 2 }),
    elevationLoss: numeric("elevation_loss", { precision: 8, scale: 2 }),
    geometries: jsonb("geometries"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => ({
    userRoutesIdx: index("idx_th_routes_user").on(table.userId, table.createdAt.desc()),
    userActiveIdx: index("idx_th_routes_active").on(table.userId, table.deletedAt, table.createdAt.desc()),
    userDateIdx: index("idx_th_routes_date").on(table.userId, table.routeDate),
  }),
);
