import type {
  GamificationAchievement,
  GamificationBadge,
  GamificationChallenge,
} from "./repository";

export const SEED_ACHIEVEMENTS: Omit<GamificationAchievement, "id" | "createdAt">[] = [
  {
    name: "First Steps",
    description: "Complete your first habit",
    icon: "star",
    xpReward: 10,
    criteriaType: "habit_count",
    criteriaValue: 1,
  },
  {
    name: "Getting Started",
    description: "Complete your first task",
    icon: "check",
    xpReward: 10,
    criteriaType: "task_count",
    criteriaValue: 1,
  },
  {
    name: "Routine Runner",
    description: "Complete your first routine",
    icon: "repeat",
    xpReward: 15,
    criteriaType: "routine_count",
    criteriaValue: 1,
  },
  {
    name: "Level Up",
    description: "Reach level 5",
    icon: "trending-up",
    xpReward: 50,
    criteriaType: "level_reached",
    criteriaValue: 5,
  },
  {
    name: "Rising Star",
    description: "Reach level 10",
    icon: "star",
    xpReward: 100,
    criteriaType: "level_reached",
    criteriaValue: 10,
  },
  {
    name: "Century",
    description: "Complete 100 habits",
    icon: "target",
    xpReward: 100,
    criteriaType: "habit_count",
    criteriaValue: 100,
  },
  {
    name: "Task Master",
    description: "Complete 50 tasks",
    icon: "clipboard-check",
    xpReward: 75,
    criteriaType: "task_count",
    criteriaValue: 50,
  },
  {
    name: "Dedicated",
    description: "Maintain a 7 day streak",
    icon: "flame",
    xpReward: 50,
    criteriaType: "streak_days",
    criteriaValue: 7,
  },
  {
    name: "Unstoppable",
    description: "Maintain a 30 day streak",
    icon: "flame",
    xpReward: 250,
    criteriaType: "streak_days",
    criteriaValue: 30,
  },
  {
    name: "Routine Champion",
    description: "Complete all routine activities for 7 days",
    icon: "repeat",
    xpReward: 100,
    criteriaType: "routine_count",
    criteriaValue: 7,
  },
  {
    name: "Challenge Accepted",
    description: "Complete your first challenge",
    icon: "award",
    xpReward: 25,
    criteriaType: "challenge_completed",
    criteriaValue: 1,
  },
  {
    name: "Challenge Enthusiast",
    description: "Complete 10 challenges",
    icon: "award",
    xpReward: 100,
    criteriaType: "challenge_completed",
    criteriaValue: 10,
  },
  {
    name: "First Promise",
    description: "Keep your first commitment",
    icon: "hand",
    xpReward: 10,
    criteriaType: "commitment_count",
    criteriaValue: 1,
  },
  {
    name: "Promise Keeper",
    description: "Keep 50 commitments",
    icon: "shield",
    xpReward: 75,
    criteriaType: "commitment_count",
    criteriaValue: 50,
  },
  {
    name: "Iron Will",
    description: "Keep 100 commitments",
    icon: "zap",
    xpReward: 150,
    criteriaType: "commitment_count",
    criteriaValue: 100,
  },
  {
    name: "Integrity Legend",
    description: "Achieve an integrity score of 95+",
    icon: "award",
    xpReward: 200,
    criteriaType: "integrity_score",
    criteriaValue: 95,
  },
  {
    name: "Unbreakable",
    description: "Maintain a 30-day integrity streak",
    icon: "flame",
    xpReward: 250,
    criteriaType: "streak_days",
    criteriaValue: 30,
  },
  {
    name: "First Grooming",
    description: "Complete your first grooming activity",
    icon: "sparkles",
    xpReward: 10,
    criteriaType: "grooming_completions",
    criteriaValue: 1,
  },
  {
    name: "Self-Care Novice",
    description: "Complete 30 grooming activities",
    icon: "heart",
    xpReward: 50,
    criteriaType: "grooming_completions",
    criteriaValue: 30,
  },
  {
    name: "Hair Care Master",
    description: "Complete 50 hair-related grooming activities",
    icon: "droplet",
    xpReward: 75,
    criteriaType: "grooming_completions",
    criteriaValue: 50,
  },
  {
    name: "Dental Champion",
    description: "Complete 100 dental care activities",
    icon: "tooth",
    xpReward: 100,
    criteriaType: "grooming_completions",
    criteriaValue: 100,
  },
  {
    name: "Grooming Pro",
    description: "Complete 500 grooming activities",
    icon: "star",
    xpReward: 200,
    criteriaType: "grooming_completions",
    criteriaValue: 500,
  },
  {
    name: "Self-Care Legend",
    description: "Complete 1000 grooming activities",
    icon: "award",
    xpReward: 500,
    criteriaType: "grooming_completions",
    criteriaValue: 1000,
  },
];

export const SEED_BADGES: Omit<GamificationBadge, "id" | "createdAt">[] = [
  {
    name: "First Habit",
    description: "Completed your first habit",
    icon: "star",
    category: "habits",
    xpReward: 10,
    criteriaType: "habit_count",
    criteriaValue: 1,
  },
  {
    name: "7 Day Streak",
    description: "Maintained a 7 day streak",
    icon: "flame",
    category: "streaks",
    xpReward: 50,
    criteriaType: "streak_days",
    criteriaValue: 7,
  },
  {
    name: "30 Day Streak",
    description: "Maintained a 30 day streak",
    icon: "flame",
    category: "streaks",
    xpReward: 200,
    criteriaType: "streak_days",
    criteriaValue: 30,
  },
  {
    name: "100 Habits",
    description: "Completed 100 habits",
    icon: "target",
    category: "habits",
    xpReward: 100,
    criteriaType: "habit_count",
    criteriaValue: 100,
  },
  {
    name: "Early Bird",
    description: "Completed a habit before 7 AM",
    icon: "sunrise",
    category: "general",
    xpReward: 20,
    criteriaType: "habit_count",
    criteriaValue: 1,
  },
  {
    name: "Night Owl",
    description: "Completed a task after 10 PM",
    icon: "moon",
    category: "general",
    xpReward: 20,
    criteriaType: "task_count",
    criteriaValue: 1,
  },
  {
    name: "Goal Crusher",
    description: "Complete 5 goals",
    icon: "target",
    category: "general",
    xpReward: 100,
    criteriaType: "task_count",
    criteriaValue: 5,
  },
  {
    name: "Routine Champion",
    description: "Maintained routines for 14 days",
    icon: "repeat",
    category: "routines",
    xpReward: 100,
    criteriaType: "routine_count",
    criteriaValue: 14,
  },
  {
    name: "Consistency King",
    description: "Maintained a streak for 60 days",
    icon: "crown",
    category: "streaks",
    xpReward: 500,
    criteriaType: "streak_days",
    criteriaValue: 60,
  },
  {
    name: "Task Tornado",
    description: "Completed 100 tasks",
    icon: "wind",
    category: "tasks",
    xpReward: 150,
    criteriaType: "task_count",
    criteriaValue: 100,
  },
  {
    name: "Man of His Word",
    description: "Kept your first commitment",
    icon: "hand",
    category: "integrity",
    xpReward: 10,
    criteriaType: "commitment_count",
    criteriaValue: 1,
  },
  {
    name: "Reliable",
    description: "Kept 25 commitments",
    icon: "shield",
    category: "integrity",
    xpReward: 50,
    criteriaType: "commitment_count",
    criteriaValue: 25,
  },
  {
    name: "Disciplined",
    description: "Kept 100 commitments",
    icon: "zap",
    category: "integrity",
    xpReward: 200,
    criteriaType: "commitment_count",
    criteriaValue: 100,
  },
  {
    name: "Consistency Master",
    description: "Maintained a 14-day integrity streak",
    icon: "flame",
    category: "integrity",
    xpReward: 100,
    criteriaType: "streak_days",
    criteriaValue: 14,
  },
  {
    name: "Promise Keeper",
    description: "Achieve 90%+ promise ratio with 50+ commitments",
    icon: "award",
    category: "integrity",
    xpReward: 300,
    criteriaType: "commitment_count",
    criteriaValue: 50,
  },
  {
    name: "Fresh Start",
    description: "Complete your first grooming activity",
    icon: "sparkles",
    category: "grooming",
    xpReward: 10,
    criteriaType: "grooming_completions",
    criteriaValue: 1,
  },
  {
    name: "Grooming Streak",
    description: "Maintained a 7-day grooming streak",
    icon: "flame",
    category: "grooming",
    xpReward: 50,
    criteriaType: "streak_days",
    criteriaValue: 7,
  },
  {
    name: "Grooming Devotee",
    description: "Complete 200 grooming activities",
    icon: "star",
    category: "grooming",
    xpReward: 100,
    criteriaType: "grooming_completions",
    criteriaValue: 200,
  },
];

export function generateChallenges(): Omit<GamificationChallenge, "id" | "createdAt">[] {
  const now = new Date();

  const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const endOfDay = new Date(startOfDay);
  endOfDay.setHours(23, 59, 59, 999);

  const startOfWeek = new Date(startOfDay);
  startOfWeek.setDate(startOfWeek.getDate() - startOfWeek.getDay());
  const endOfWeek = new Date(startOfWeek);
  endOfWeek.setDate(endOfWeek.getDate() + 7);
  endOfWeek.setHours(23, 59, 59, 999);

  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);
  endOfMonth.setHours(23, 59, 59, 999);

  return [
    {
      name: "5 Habits Today",
      description: "Complete 5 habits today",
      challengeType: "daily",
      criteriaType: "habit_count",
      criteriaValue: 5,
      xpReward: 30,
      badgeId: null,
      startsAt: startOfDay,
      endsAt: endOfDay,
      isActive: true,
    },
    {
      name: "3 Tasks Today",
      description: "Finish 3 tasks today",
      challengeType: "daily",
      criteriaType: "task_count",
      criteriaValue: 3,
      xpReward: 25,
      badgeId: null,
      startsAt: startOfDay,
      endsAt: endOfDay,
      isActive: true,
    },
    {
      name: "Complete a Routine",
      description: "Complete a routine today",
      challengeType: "daily",
      criteriaType: "routine_count",
      criteriaValue: 1,
      xpReward: 30,
      badgeId: null,
      startsAt: startOfDay,
      endsAt: endOfDay,
      isActive: true,
    },
    {
      name: "Weekly Habit Blitz",
      description: "Complete 30 habits this week",
      challengeType: "weekly",
      criteriaType: "habit_count",
      criteriaValue: 30,
      xpReward: 100,
      badgeId: null,
      startsAt: startOfWeek,
      endsAt: endOfWeek,
      isActive: true,
    },
    {
      name: "Weekly Task Sprint",
      description: "Finish 15 tasks this week",
      challengeType: "weekly",
      criteriaType: "task_count",
      criteriaValue: 15,
      xpReward: 75,
      badgeId: null,
      startsAt: startOfWeek,
      endsAt: endOfWeek,
      isActive: true,
    },
    {
      name: "Routine Perfection Week",
      description: "Complete all routines every day this week",
      challengeType: "weekly",
      criteriaType: "routine_count",
      criteriaValue: 7,
      xpReward: 100,
      badgeId: null,
      startsAt: startOfWeek,
      endsAt: endOfWeek,
      isActive: true,
    },
    {
      name: "Monthly Habit Marathon",
      description: "Complete 100 habits this month",
      challengeType: "monthly",
      criteriaType: "habit_count",
      criteriaValue: 100,
      xpReward: 300,
      badgeId: null,
      startsAt: startOfMonth,
      endsAt: endOfMonth,
      isActive: true,
    },
    {
      name: "Monthly Task Challenge",
      description: "Finish 50 tasks this month",
      challengeType: "monthly",
      criteriaType: "task_count",
      criteriaValue: 50,
      xpReward: 200,
      badgeId: null,
      startsAt: startOfMonth,
      endsAt: endOfMonth,
      isActive: true,
    },
    {
      name: "5 Grooming Today",
      description: "Complete 5 grooming activities today",
      challengeType: "daily",
      criteriaType: "grooming_completions",
      criteriaValue: 5,
      xpReward: 25,
      badgeId: null,
      startsAt: startOfDay,
      endsAt: endOfDay,
      isActive: true,
    },
    {
      name: "Grooming Streak Week",
      description: "Complete 25 grooming activities this week",
      challengeType: "weekly",
      criteriaType: "grooming_completions",
      criteriaValue: 25,
      xpReward: 75,
      badgeId: null,
      startsAt: startOfWeek,
      endsAt: endOfWeek,
      isActive: true,
    },
    {
      name: "Monthly Grooming Marathon",
      description: "Complete 100 grooming activities this month",
      challengeType: "monthly",
      criteriaType: "grooming_completions",
      criteriaValue: 100,
      xpReward: 250,
      badgeId: null,
      startsAt: startOfMonth,
      endsAt: endOfMonth,
      isActive: true,
    },
  ];
}
