export {
  musicArtists,
  musicAlbums,
  musicTracks,
  musicListeningHistory,
  musicJournal,
  musicMemories,
  musicRatings,
  musicFavorites,
  musicCollections,
  musicCollectionItems,
  musicGoalConfig,
  musicSpotifyTokens,
} from "./schema";

export {
  searchArtists,
  searchAlbums,
  searchTracks,
  logListening,
  getListeningHistory,
  createJournalEntry,
  getJournalEntries,
  getJournalEntry,
  updateJournalEntry,
  deleteJournalEntry,
  createMemory,
  getMemories,
  deleteMemory,
  createRating,
  getRatings,
  updateRating,
  deleteRating,
  addFavorite,
  getFavorites,
  removeFavorite,
  createCollection,
  getCollections,
  getCollection,
  updateCollection,
  deleteCollection,
  addCollectionItem,
  removeCollectionItem,
  createGoalConfig,
  getGoalConfigs,
  updateGoalConfig,
  deleteGoalConfig,
  getAnalytics,
  syncArtistFromSpotify,
  syncAlbumFromSpotify,
  syncTrackFromSpotify,
  searchQuerySchema,
  createListeningSchema,
  createJournalSchema,
  updateJournalSchema,
  createMemorySchema,
  createRatingSchema,
  updateRatingSchema,
  createFavoriteSchema,
  createCollectionSchema,
  updateCollectionSchema,
  addCollectionItemSchema,
  createGoalConfigSchema,
  updateGoalConfigSchema,
} from "./service";

export type {
  SearchQueryParams,
  CreateListeningParams,
  CreateJournalParams,
  UpdateJournalParams,
  CreateMemoryParams,
  CreateRatingParams,
  UpdateRatingParams,
  CreateFavoriteParams,
  CreateCollectionParams,
  UpdateCollectionParams,
  AddCollectionItemParams,
  CreateGoalConfigParams,
  UpdateGoalConfigParams,
} from "./service";

export type {
  Artist,
  Album,
  Track,
  ListeningEntry,
  MusicJournalEntry,
  Memory,
  Rating,
  Favorite,
  Collection,
  CollectionItem,
  GoalConfig,
} from "./repository";
