export {
  createJournalEntry,
  getJournalEntry,
  getJournalEntries,
  updateJournalEntry,
  deleteJournalEntry,
  getJournalStats,
  getJournalCoverageForUser,
  saveJournalEntryVersion,
  getJournalEntryVersions,
  restoreJournalEntryVersion,
  addBookmark,
  getEntryBookmarksForUser,
  removeBookmark,
  addHighlight,
  getEntryHighlightsForUser,
  modifyHighlight,
  removeHighlight,
  startJournalWritingSession,
  stopJournalWritingSession,
  getJournalEntrySessions,
  getJournalSessionStats,
  exportEntryAsMarkdown,
  exportEntryAsJson,
} from "./service";
export type {
  CreateEntryParams,
  UpdateEntryParams,
  JournalFiltersParams,
  CreateVersionParams,
  CreateBookmarkParams,
  CreateHighlightParams,
  UpdateHighlightParams,
} from "./service";
export type { JournalEntry, JournalVersion, JournalBookmark, JournalHighlight, JournalWritingSession } from "./repository";
export { computeStreak, computeReadingTime, formatDate, getMoodEmoji, getMoodColor } from "./utils";
