export {
  books,
  bookParts,
  bookChapters,
  bookVersions,
  bookCollaborators,
  bookComments,
  bookReadingProgress,
  bookBookmarks,
  bookHighlights,
  bookCharacters,
  bookResearchNotes,
  bookChapterCharacters,
  bookChapterResearchNotes,
  bookWritingSessions,
} from "./schema";

export {
  createNewBook,
  getBooks,
  getBook,
  updateExistingBook,
  removeBook,
  getDashboard,
  addPart,
  getParts,
  modifyPart,
  removePart,
  addChapter,
  getChapters,
  getChapter,
  modifyChapter,
  removeChapter,
  reorderBookChapters,
  saveVersion,
  getChapterVersions,
  restoreVersion,
  inviteCollaborator,
  getBookCollaborators,
  modifyCollaborator,
  removeCollaborator,
  checkCollaboratorRole,
  addComment,
  getChapterComments,
  editComment,
  removeComment,
  saveReadingProgress,
  getBookProgress,
  getRecentProgress,
  addBookmark,
  getBookBookmarks,
  removeBookmark,
  addHighlight,
  getBookHighlights,
  modifyHighlight,
  removeHighlight,
  searchAllBooks,
  exportBookAsMarkdown,
  exportBookAsJson,
  addCharacter,
  getCharacters,
  modifyCharacter,
  removeCharacter,
  addResearchNote,
  getResearchNotes,
  modifyResearchNote,
  removeResearchNote,
  linkCharacterToChapter,
  getChapterCharacters,
  unlinkCharacterFromChapter,
  linkResearchNoteToChapter,
  getChapterResearchNotes,
  unlinkResearchNoteFromChapter,
  startWritingSession,
  endWritingSession,
  getBookSessions,
  getSessionStats,
} from "./service";

export {
  createBookSchema,
  updateBookSchema,
  createPartSchema,
  updatePartSchema,
  createChapterSchema,
  updateChapterSchema,
  createCollaboratorSchema,
  updateCollaboratorSchema,
  createCommentSchema,
  updateCommentSchema,
  createBookmarkSchema,
  createHighlightSchema,
  updateHighlightSchema,
  upsertProgressSchema,
  createCharacterSchema,
  updateCharacterSchema,
  createResearchNoteSchema,
  updateResearchNoteSchema,
  linkChapterCharacterSchema,
  linkChapterResearchNoteSchema,
  createWritingSessionSchema,
} from "./service";

export type {
  CreateBookParams,
  UpdateBookParams,
  CreatePartParams,
  CreateChapterParams,
  UpdateChapterParams,
  CreateCollaboratorParams,
  CreateCommentParams,
  UpsertProgressParams,
  CreateBookmarkParams,
  CreateHighlightParams,
  UpdateHighlightParams,
  CreateCharacterParams,
  UpdateCharacterParams,
  CreateResearchNoteParams,
  UpdateResearchNoteParams,
  LinkChapterCharacterParams,
  LinkChapterResearchNoteParams,
  CreateWritingSessionParams,
} from "./service";

export type {
  Book,
  BookPart,
  BookChapter,
  BookVersion,
  BookCollaborator,
  BookComment,
  BookReadingProgress,
  BookBookmark,
  BookHighlight,
} from "./repository";
